Django/EventRegApi/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from Userreg import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.index,name='index'),
    url(r'^special/',views.special,name='special'),
    url(r'^Userreg/',include('Userreg.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
]

Django/Userreg/urls.py
from django.conf.urls import url
from Userreg import views
# SET THE NAMESPACE!
app_name = 'Userreg'
# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login'),
    url(r'^Cevent/$',views.Cevent,name='Cevent'),
    url('',views.EventList.as_view(),name='Eevent'),
    url('', views.EventDelete.as_view(), name='Devent'),
    url('', views.EventDetail.as_view(), name='event-detail'),
    url('', views.attend_event, name='attend_event'),
    url('', views.not_attend_event, name='not_attend_event'),
]

Django/Userreg/models.py
from django.db import models
from django.conf import settings
from django.shortcuts import reverse
from django.contrib.auth.models import User
'''from tinymce.models import HTMLField'''
# Create your models here.
class UserProfileInfo(models.Model):
	user = models.OneToOneField(User,on_delete=models.CASCADE)
	portfolio_site = models.URLField(blank=True)
	profile_pic = models.ImageField(upload_to='profile_pics',blank=True)
	def __str__(self):
	  return self.user.username
class Event(models.Model):
    name = models.CharField(max_length=50)
    venue = models.CharField(max_length=200)
    date = models.DateField(help_text='Please use the following format: <em>YYYY-MM-DD</em>.')
    time = models.TimeField(help_text='Please use the following format: <em>HH:MM:SS<em>')
    category = models.CharField(max_length=50)
    num_of_attendees = models.PositiveIntegerField(default=0, blank=True)
    attendees = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='attending', blank=True)

    class Meta:
        verbose_name = 'event'
        verbose_name_plural = 'events'
        ordering = ['date', 'time']

    def get_absolute_url(self):
        return reverse('Userreg:event-detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.name

    def get_number_of_attendeess(self):
        return self.attendees.all().count()

    def get_number_of_attendees(self):
        return self.num_of_attendees

Django/Userreg/forms.py
from django import forms
from Userreg.models import UserProfileInfo
from django.contrib.auth.models import User
'''from tinymce import TinyMCE'''
from .models import Event
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','password','email')
class UserProfileInfoForm(forms.ModelForm):
    class Meta():
         model = UserProfileInfo
         fields = ('portfolio_site','profile_pic')
class EventForm(forms.ModelForm):
	class Meta():
		model=Event
		fields = ('category', 'name', 'venue', 'time', 'date','num_of_attendees',)

Django/Userreg/views.py
from django.shortcuts import render
from Userreg.forms import UserForm,UserProfileInfoForm,EventForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.views import generic
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.models import User
from django.views import View
from .models import Event
def index(request):
    return render(request,'Userreg/index.html')
@login_required
def Cevent(request):
    Created = False
    if request.method == 'POST':
        event_form = EventForm(data=request.POST)
        if event_form.is_valid():
            event = event_form.save()
            event.save()
            Created = True
        else:
            print(event_form.errors)
    else:
        event_form = EventForm()
    return render(request,'Userreg/Cevent.html',
                          {'event_form':event_form,
                           'Created':Created})
@login_required
def special(request):
    return HttpResponse("You are logged in !")
@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))
def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            if 'profile_pic' in request.FILES:
                print('found it')
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()
            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    return render(request,'Userreg/registration.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})
def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Your account was inactive.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details given")
    else:
        return render(request, 'Userreg/login.html', {})
# Create your views here.
class EventList(LoginRequiredMixin, generic.ListView):
    model = Event
    template_name = 'Userreg/Eevent.html'
    context_object_name = 'events'
    paginate_by = 10

    def get_queryset(self):
        if self.request.user.is_superuser:
            return Event.objects.all()
        else:
            return Event.objects.all()

class EventDetail(LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        view = EventDisplay.as_view()
        return view(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        view = CommentCreate.as_view()
        return view(request, *args, **kwargs)

class EventDelete(LoginRequiredMixin, SuccessMessageMixin, generic.DeleteView):
    model = Event
    template_name = 'Userreg/delete.html'
    success_url = reverse_lazy('Userreg:Eevent')
    context_object_name = 'event'
    success_message = "%(name)s was deleted successfully"

@login_required()
def attend_event(request, event_id):
    event = get_object_or_404(Event, pk=event_id)
    attendee = User.objects.get(username=request.user)
    event.attendees.add(attendee)
    create_action(attendee, 'is attending', event)
    messages.success(request, 'You are now attending {0}'.format(event.name))
    return redirect('events:event-detail', pk=event.pk)


@login_required()
def not_attend_event(request, event_id):
    event = get_object_or_404(Event, pk=event_id)
    attendee = User.objects.get(username=request.user)
    event.attendees.remove(attendee)
    create_action(attendee, 'no longer attending', event)
    messages.success(request, 'You are no longer attending {0}'.format(event.name))
    return redirect('events:event-detail', pk=event.pk)

Django/templates/Userreg/Cevent.html
{% extends "Userreg/base.html" %}
{% load staticfiles %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if Created %}
        <h1>Thank you for Creating an event!</h1>
      {% else %}
        <h1>Create Event Here</h1>
<form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ event_form.as_p }}
          <input type="submit" name="" value="Create">
        </form>
        
      {% endif %}
    </div>
  </div>
{% endblock %}

Django/templates/Userreg/Devent.html
{% extends "Userreg/base.html" %}
{% load staticfiles %}
{% block body_block %}
        {% for event in events %}
            <p></p>
            <div class="card w-75 mx-auto border-info">
                <div class="card-body">
                    <div>
                        <p class="card-text"><strong>{{ event.venue|upper }}</strong></p>
                        <h2><a class="card-text text-info">{{event.name}}</a></h2>
                        <p class="card-text"><small class="text-muted">{{ event.time }}</small></p>
                        <div>
                            <a class="btn btn-danger btn-sm active">delete</a>

                        </div>
                    </div>
                </div>
            </div>

        {% endfor %}

    {% endblock %}

Django/templates/Userreg/Eevent.html
{% extends "Userreg/base.html" %}
{% load staticfiles %}
{% block body_block %}
        {% for event in events %}
            <div class="card w-50 mx-auto border-info">
                <div class="card-body">
                    <div>
                        <h2><a class="card-text text-info"href="{% url 'Userreg:event-detail' %}">{{event.name}}</a></h2>
                        <span class="card-text">Venue:<strong> {{ event.venue|upper }} </strong> - <span class="mx-auto w-50"><strong>{{ event.date }}</strong></span> - <small class="text-muted">Time: <strong>{{ event.time }}</strong></small></span><br>
                        <span class="card-text">Number of attendees :<strong>{{ event.get_number_of_attendees }}</strong></span>
                        <p class="card-text">Event Organizer:<strong> {{ user.username}} </strong>   -   <small class="text-muted">Email: {{ user.email }}</small></p>
                    </div>


                </div>
            </div>
            <br>
        {% endfor %}


    {% endblock %}

Django/templates/Userreg/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
{# Django Home Link / Admin Link / Register Link#}
          <li><a class="navbar-brand" href="{% url 'index' %}">Home</a></li>    
          {# Some logic on what to display for last item#}
          {% if user.is_authenticated %}
          	<li><a class="navbar-link" href="{% url 'Userreg:Cevent' %}">  Create Event   </a></li>
          	<li><a class="navbar-link" href="{% url 'Userreg:Devent' %}">  My Events   </a></li>
          	<li><a class="navbar-link" href="{% url 'Userreg:Eevent' %}">  Explore Events   </a></li>
            <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
          	<li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li> 
            <li><a class="navbar-link" href="{% url 'Userreg:register' %}">Register</a></li>
            <li><a class="navbar-link" href="{% url 'Userreg:user_login' %}">Login</a></li>
          {% endif %}
</ul>
      </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>
  </body>
</html>

Django/templates/Userreg/event-detail.html
{% extends 'Userreg/base.html' %}
{% load staticfiles %}
{% block body_block %}
      <div class="card">
        <div class="card-body">
            <h3 class="card-text"><small>Organizer: {{ event.creator|capfirst }}</small></h3>
            <h1 class="card-text">{{ event.name }}</h1>
            <h3 class="card-text text-muted float-left">{{ event.date }}; </h3>

            <h3 class="card-text text-muted">{{ event.time }}</h3>
            {% if request.user in attending %}
                <a class="btn btn-danger btn active w-25" href="{% url 'Userreg:not_attend_event' event.id %}">Not Attending</a>
            {% else %}
                <a class="btn btn-success btn active w-25" href="{% url 'Userreg:attend_event' event.id %}">Attend</a>

            {% endif %}
        </div>
      </div>

      <!--<div class="jumbotron w-75 mx-auto">
        <h1 class="display-4">Details</h1>
        <p class="lead">{{ event.details|safe }}</p>
      </div>-->



    <div class="mx-auto w-75">
        <h2>{{ event.get_number_of_attendeess }} Attending</h2>
            <div class="card card-body">
                {% for attendee in attending %}
                    <p>{{ attendee.username|capfirst }}</p>

                {% endfor %}

            </div>
        </div>
    </div>
<!--
    <div>
        <h2 class="w-75 mx-auto">{{ event.get_comments_number }} Comments</h2>
      {% for comment in comments %}
          {% if not comment.get_parents %}

              <div class="media card w-75 mx-auto border-dark">
                <div class="media-body card-body">
                    <h4 class="card-text">{% cloudinary comment.get_comment_creator_photo width=45 height=45 radius='max' crop='fill' %}{{ comment.created_by }}</h4>
                    <p class="card-text">{{ comment.comment }}</p>
                    <a href="{% url 'comments:comment-detail' comment.id event.id %}">Reply</a>

                    {% if comment.get_children %}

                    <div class="media card mx-auto">
                        <div class="media-body card-body">
                            {% for child in comment.get_children %}
                                <h4 class="card-text">{% cloudinary child.get_comment_creator_photo width=45 height=45 radius='max' crop='fill' %}{{ child.created_by }}</h4>
                                <p class="card-text">{{ child.comment }}</p>
                                <a href="{% url 'comments:comment-detail' child.id event.id %}">Reply</a>

                                {% if child.get_children %}

                                <div class="media card mx-auto">
                                    <div class="media-body card-body">
                                        {% for grandchild in child.get_children %}
                                            <h4 class="card-text">{% cloudinary comment.get_comment_creator_photo width=45 height=45 radius='max' crop='fill' %}{{ grandchild.created_by }}</h4>
                                            <p class="card-text">{{ grandchild.comment }}</p>
                                        {% endfor %}

                                    </div>
                                </div>
                                {% else %}
                                {% endif %}
                            {% endfor %}
                        </div>
                    {% else %}
                    {% endif %}
                    </div>
                </div>
              </div>
              <br>
          {% endif %}


      {%  endfor %}

    </div>

    <div>

    </div>

   <!-- <div class="mx-auto w-100">
      <form class="mx-auto w-50" method="post"> {% csrf_token %}
        {{ form|crispy }}
        <button class="mx-auto btn btn-primary btn-lg active w-25" type="submit">Add comment</button>
      </form>


    </div>-->-->

  {% endblock %}

Django/templates/Userreg/index.html
{% extends "Userreg/base.html" %}
{% block body_block %}
<div class="container">
  <div class="jumbotron">
    <h1>Welcome to the Event Registration Api !</h1>
    {% if user.is_authenticated %}
        <h2>Hello {{ user.username }}</h2>
    {% else %}
        <h2>Register or Login if you'd like to</h2>
    {% endif %}
  </div>
</div>
{% endblock %}

Django/templates/Userreg/login.html
{% extends 'Userreg/base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Login here :</h1>
<form method="post" action="{% url 'Userreg:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">
<label for="password">Password:</label>
          <input type="password" name="password" placeholder="Password">
<input type="submit" name="" value="Login">
</form>
</div>
  </div>
{% endblock %}

Django/templates/Userreg/registration.html
{% extends "Userreg/base.html" %}
{% load staticfiles %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
<form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          <!--{{ profile_form.as_p }}-->
          <input type="submit" name="" value="Register">
        </form>
        
      {% endif %}
    </div>
  </div>
{% endblock %}